### PR TITLE
Prepare for support of multiple OIDC providers

### PR DESCRIPTION
**Pull request by koriaf**
With these improvements now it's possible to write auth backend, which support multiple OIDC providers and dynamic determination which one is to use for given JWT.

### CODE REVIEW

**Comment by allardhoeve** [comment]
Thanks! It looks like a nice feature. I'm not sure why the tests fail, I'll have a look at that shortly.

**Comment by allardhoeve** [comment]
Thanks! The failing tests were unrelated, and I fixed them in #18.

**Comment by allardhoeve** [comment]
So I've tagged and released 0.9 with this feature. Thanks.

**Comment by koriaf** [comment]
Good :-) but it's not feature yet, it's just prepare for this feature. I have the custom class MultipleProvidersJWTAuthentication, inherited from JSONWebTokenAuthentication, which does the trick; planned to release it as pr later but lack the time to finish it, document and write tests.

Hopefully will do it soon. It works for me at least - it determines dynamically the OIDC provider, against which to validate given JWT, from the jwt content, `iss` field.

**Comment by koriaf** [comment]
By the way, here is full version of current code, but it's full with side-effects and without any documentation/tests yet. You can review it, if you are interested :-)
Or just wait till I have opportunity to finish it.
https://gist.github.com/koriaf/87db92999ec6c2d3a755134a274d4d29

**Comment by allardhoeve** [comment]
Cool! We might need it next year, so I would be very interested.

**Pull request merged**
