### PR TITLE
Protect cache decorator with a mutex

### PR DESCRIPTION
**Pull request by juyrjola**
When running in a multithreaded environment (such as runserver),
sometimes add_to_cache raises an exception because the key is
already in the cache. It's because of a race condition in `__call__()`.

Fix it by protecting the critical section with `threading.Lock`.

### CODE REVIEW

**Comment by kerrermanisNL** [comment]
Thanks for the PR @juyrjola!

**Comment by dedsm** [comment]
hey I noticed this is merged, but I think it's forcing the threads to be synchronous even when the value is cached, which kind of defeats the concurrency purpose, I wrote it like this:

```python
        def wrapped(this, *args):
            now = time.time()
            self.purge_expired(now)

            cached_value = self.get_from_cache(args)

            if cached_value is None:
                with self.lock:
                    cached_value = self.get_from_cache(args)
                    if cached_value is None:
                        cached_value = fn(this, *args)
                        self.add_to_cache(args, cached_value, now)
            return cached_value
```

a double if but prevents locking if not necessary, thoughts?

**Comment by juyrjola** [comment]
That seems unnecessary, because both `purge_expired()` and `get_from_cache()` are very fast operations.

**Comment by juyrjola** [comment]
Oh, and thanks for merging the PR! I had already forgotten about it myself. :smile:

**Pull request merged**
